### ISSUE TITLE
Doesn't work with multicursors

### ISSUE THREAD

**Issue by SoftwareApe** [trentrand/vscode-git-rebase#2]
When selecting with multicursors it doesn't work:
![grafik](https://user-images.githubusercontent.com/17566442/81399825-09f71e00-912c-11ea-8737-b3948624a521.png)

Only the first entry is changed:
![grafik](https://user-images.githubusercontent.com/17566442/81399829-0cf20e80-912c-11ea-9b3c-feb5c4ab346f.png)

**Comment by trentrand** [comment]
This issue has been fixed in Pull Request #3 and released as version 1.1.0 alongside some dependency upgrades.

I've published it as [trentrand.git-rebase-shortcuts@1.1.0](https://marketplace.visualstudio.com/items?itemName=trentrand.git-rebase-shortcuts) to the Visual Studio Extension Marketplace.

I'm going to close this issue as fixed, but please leave a comment once you give it a try.

Thank you for filing the issue and providing a fix!
